### ISSUE TITLE
Is there any guidance on how to set the value of α in Equation 4?

### ISSUE THREAD

**Issue by HWalkingMan** [jaeill/CVPR23-VNE#1]
I would like to use your amazing VNE Regularization method in my own network, but am struggling to choose the right α, any good ideas?
P.S.: I want to use it in a GAN-based face blind reconstruction model
P.P.S.:Equation 4
![image](https://github.com/jaeill/CVPR23-VNE/assets/47980785/789a9949-b1f9-4fb8-8474-94945037630e)

**Comment by jaeill** [comment]
We express our gratitude for your keen interest in our study.
For GAN experiments, we adopt a systematic search for the optimal value of the parameter alpha. We commence the search with relatively large values, such as 0.5, and progressively decrease it towards smaller magnitudes, such as 0.05.
For example, we employ an alpha value of 0.10 for WGAN-GP, 0.25 for PD-GAN, and 0.35 for both DCGAN and BigGAN.
